-- Supabase SQL Editor에서 그대로 실행하세요.
-- 전문진단 요청 저장용 테이블입니다.
-- 업로드 이미지는 저장하지 않고, 전화번호와 진단 요약만 저장합니다.

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  phone text not null,
  source text default 'portfolio_diagnosis',
  grade text,
  score numeric,
  detected_app text,
  summary text,
  holdings_count integer default 0,
  consent boolean default true,
  created_at timestamptz default now()
);

create index if not exists consultation_requests_created_at_idx
on public.consultation_requests (created_at desc);

-- 외부 공개 접근은 막고, Vercel 서버의 service role key로만 접근합니다.
alter table public.consultation_requests enable row level security;

-- 별도 public policy를 만들지 마세요.
-- service_role key는 RLS를 우회하므로 서버 API에서만 insert/select 합니다.
